<a href="https://colab.research.google.com/github/ellianorsX/AI_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd

In [6]:
print(pd.__version__)

2.2.3

In [10]:


mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Toyota", "BMW", "Volvo"],
  'counts': [3, 7, 2, 4, 6, 7]
}

df = pd.DataFrame(mydataset)
print(df)

     cars  counts
0     BMW       3
1   Volvo       7
2    Ford       2
3  Toyota       4
4     BMW       6
5   Volvo       7

In [12]:
df.head() #default 5 rows

     cars  counts
0     BMW       3
1   Volvo       7
2    Ford       2
3  Toyota       4
4     BMW       6

In [13]:
df.tail() #default 5 rows

     cars  counts
1   Volvo       7
2    Ford       2
3  Toyota       4
4     BMW       6
5   Volvo       7

In [15]:
df.shape

(6, 2)

In [17]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [19]:
df.dtypes

cars      object
counts     int64
dtype: object

In [20]:
df.describe() #numerical columns only

         counts
count  6.000000
mean   4.833333
std    2.136976
min    2.000000
25%    3.250000
50%    5.000000
75%    6.750000
max    7.000000

In [22]:
df.iloc[0]

cars      BMW
counts      3
Name: 0, dtype: object

In [23]:
df.loc[2:5]

     cars  counts
2    Ford       2
3  Toyota       4
4     BMW       6
5   Volvo       7

In [24]:
df[df["counts"] !=3 ]

     cars  counts
1   Volvo       7
2    Ford       2
3  Toyota       4
4     BMW       6
5   Volvo       7

In [26]:
df.mean(numeric_only=True)

counts    4.833333
dtype: float64

In [27]:
df.min()

cars      BMW
counts      2
dtype: object

In [28]:
df.max()

cars      Volvo
counts        7
dtype: object

In [29]:
df.sum()

cars      BMWVolvoFordToyotaBMWVolvo
counts                            29
dtype: object

In [30]:
df.median(numeric_only=True)

counts    5.0
dtype: float64

In [31]:
df.count()

cars      6
counts    6
dtype: int64

In [32]:
df.std(numeric_only=True)

counts    2.136976
dtype: float64

In [33]:
from os import NGROUPS_MAX
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Toyota", None, "Volvo"],
    'counts': [3, 7, None, 4, None, 7]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

     cars  counts
0     BMW     3.0
1   Volvo     7.0
2    None     NaN
3  Toyota     4.0
4    None     NaN
5   Volvo     7.0

In [35]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [36]:
df_missing.dropna()

     cars  counts
0     BMW     3.0
1   Volvo     7.0
3  Toyota     4.0
5   Volvo     7.0

In [37]:
df_missing.dropna(subset=['cars'])

     cars  counts
0     BMW     3.0
1   Volvo     7.0
3  Toyota     4.0
5   Volvo     7.0

In [38]:
df_missing.fillna(0)

     cars  counts
0     BMW     3.0
1   Volvo     7.0
2       0     0.0
3  Toyota     4.0
4       0     0.0
5   Volvo     7.0

In [41]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head(100)

# df = pd.read_exel(fayl nomi)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [45]:
df.to_json("sample_date")